close all;
specFlux('track201-classical.wav');
specFlux('track204-classical.wav');
specFlux('track370-electronic.wav');
specFlux('track396-electronic.wav');
specFlux('track437-jazz.wav');
specFlux('track439-jazz.wav');
specFlux('track463-metal.wav');
specFlux('track492-metal.wav');
specFlux('track547-rock.wav');
specFlux('track550-rock.wav');
specFlux('track707-world.wav');
specFlux('track729-world.wav');

specFlat('track201-classical.wav');
specFlat('track204-classical.wav');
specFlat('track370-electronic.wav');
specFlat('track396-electronic.wav');
specFlat('track437-jazz.wav');
specFlat('track439-jazz.wav');
specFlat('track463-metal.wav');
specFlat('track492-metal.wav');
specFlat('track547-rock.wav');
specFlat('track550-rock.wav');
specFlat('track707-world.wav');
specFlat('track729-world.wav');
close all;