%build everything necessary for report
clear filename song Xk mfccp specHistogram sim ARm NPCP;
close all;
fileArray = cellstr([
    'track201-classical.wav '; ...
    'track204-classical.wav '; ...
    'track370-electronic.wav'; ...
    'track370-electronic.wav'; ...
    'track396-electronic.wav'; ...
    'track437-jazz.wav      '; ...
    'track439-jazz.wav      '; ...
    'track463-metal.wav     '; ...
    'track492-metal.wav     '; ...
    'track547-rock.wav      '; ...
    'track550-rock.wav      '; ...
    'track707-world.wav     '; ...
    'track729-world.wav     '
    ]);
fbank=melBank();
len=length(fileArray);
parfor i=1:12
    filename=['' fileArray{i} ''];
    song=extractSound(filename);
    Xk=freqDist(song);
    mfccp=mfcc(fbank,Xk);
    specHistogram=spectrumHistogram(filename,mfccp,1);
    sim=simMatrix(mfccp,filename,1);
    rhythmIndex(filename,sim,1);
    autoC(filename,sim,1);
    ARm=rhythmVar( filename,sim,1);
    NPCP=normPCP(filename,song,1);
end